// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ticketing.Infrastructure.Persistence;

#nullable disable

namespace Ticketing.Infrastructure.Migrations
{
    [DbContext(typeof(TicketingDbContext))]
    partial class TicketingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Ticketing.Domain.Entities.AppliedTicketModification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("AppliedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("applied_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<int>("AppliedOrder")
                        .HasColumnType("int")
                        .HasColumnName("applied_order");

                    b.Property<string>("ModificationCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modification_code");

                    b.Property<string>("ParamsUsed")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("params_used");

                    b.Property<int>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1)
                        .HasColumnName("quantity");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rule_type");

                    b.Property<decimal>("Surcharge")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("surcharge");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("applied_ticket_modifications", null, t =>
                        {
                            t.HasCheckConstraint("CHK_applied_params_json", "ISJSON([params_used]) = 1");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.CurrentFareRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2")
                        .HasColumnName("effective_from");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("params");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("policy_code");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("PolicyCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_current_fare_rates_policy");

                    b.ToTable("current_fare_rates", null, t =>
                        {
                            t.HasCheckConstraint("CHK_current_fare_rates_json", "ISJSON([params]) = 1");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.CurrentModificationRule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("ModificationCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("modification_code");

                    b.Property<string>("ParamsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("params");

                    b.Property<int>("Priority")
                        .HasColumnType("int")
                        .HasColumnName("priority");

                    b.Property<string>("RuleType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("rule_type");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("Id");

                    b.HasIndex("ModificationCode")
                        .IsUnique()
                        .HasDatabaseName("UQ_current_mod_rules_code");

                    b.ToTable("current_modification_rules", null, t =>
                        {
                            t.HasCheckConstraint("CHK_current_mod_rules_json", "ISJSON([params]) = 1");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.FareCalculationSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BaseFareInputs")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("base_fare_inputs");

                    b.Property<DateTime>("CalculatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("calculated_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("PolicyCode")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("policy_code");

                    b.Property<long>("TicketId")
                        .HasColumnType("bigint")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.ToTable("fare_calculation_snapshots", null, t =>
                        {
                            t.HasCheckConstraint("CHK_snapshot_inputs_json", "ISJSON([base_fare_inputs]) = 1");
                        });
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Ticket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("base_fare");

                    b.Property<DateTime>("IssuedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("issued_at")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("ticket_number");

                    b.Property<string>("ProductType")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("product_type");

                    b.Property<decimal>("TotalFare")
                        .HasColumnType("decimal(10,2)")
                        .HasColumnName("total_fare");

                    b.HasKey("Id");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("UQ_tickets_ticket_number");

                    b.ToTable("tickets", (string)null);
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.AppliedTicketModification", b =>
                {
                    b.HasOne("Ticketing.Domain.Entities.Ticket", null)
                        .WithMany("AppliedModifications")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.FareCalculationSnapshot", b =>
                {
                    b.HasOne("Ticketing.Domain.Entities.Ticket", null)
                        .WithOne("Snapshot")
                        .HasForeignKey("Ticketing.Domain.Entities.FareCalculationSnapshot", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ticketing.Domain.Entities.Ticket", b =>
                {
                    b.Navigation("AppliedModifications");

                    b.Navigation("Snapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
